import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.detekt)
}

android {
    namespace = "com.sap.codelab"
    compileSdk = Integer.parseInt(libs.versions.compileSdk.get())
    buildToolsVersion = "36.0.0"

    defaultConfig {
        applicationId = "com.sap.codelab"
        minSdk = Integer.parseInt(libs.versions.minSdk.get())
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(
                    getDefaultProguardFile("proguard-android.txt"),
                    "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    buildFeatures {
        viewBinding = true
    }
}

kotlin {
    target {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_21
        }
    }
}

detekt {
    toolVersion = "1.23.8"
    buildUponDefaultConfig = true
    allRules = false
    config = files("$rootDir/detekt.yml")
    source = files("src/main/kotlin", "src/test/kotlin")
    parallel = true
}

dependencies {
    implementation(fileTree("libs") { include("*.jar") })
    //AndroidX
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.google.material)

    //Lifecycle, LiveData and ViewModel dependencies
    implementation(libs.bundles.lifecycle)

    //Room persistence
    implementation(libs.bundles.room)
    ksp(libs.room.compiler)

    //Coroutines
    implementation(libs.bundles.coroutines)

    // DI-Koin
    implementation(libs.koin.android)

    // Google Maps
    implementation(libs.play.services.maps)
    implementation(libs.play.services.location)

    detektPlugins(libs.detekt.formatting)

    // Testing
    testImplementation(libs.test.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockk)
    androidTestImplementation(libs.androidx.room.testing)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}
